(function(){let p=[],t={lang:"all",tag:null,search:""};function b(){const e=new URLSearchParams(window.location.search);return{lang:e.get("lang")||"all",tag:e.get("tag")||null,search:e.get("q")||"",page:parseInt(e.get("page"))||1}}function c(e){const a=new URLSearchParams(window.location.search);Object.entries(e).forEach(([l,r])=>{r===null||r===""||r==="all"||r===1?a.delete(l):a.set(l,r)});const n=a.toString()?`${window.location.pathname}?${a.toString()}`:window.location.pathname;window.history.pushState({},"",n)}async function y(){try{p=await(await fetch("/tags.json")).json()}catch(e){console.error("Failed to load tags:",e),p=[]}}function o(){document.querySelectorAll(".article-card").forEach(a=>{let n=!0;if(t.lang!=="all"){const l=a.getAttribute("data-language")||"en";t.lang==="pt"?n=n&&(l==="pt-BR"||l==="pt"):n=n&&l===t.lang}if(t.tag){const l=a.getAttribute("data-tags")||"";n=n&&l.includes(t.tag.toLowerCase())}n?a.style.display="":a.style.display="none"}),window.pagination&&window.pagination.handleSearch&&window.pagination.handleSearch()}function u(){document.querySelectorAll(".tag-pill").forEach(a=>{const n=a.getAttribute("data-tag");n==="all"&&!t.tag||n===t.tag?a.className="tag-pill px-4 py-1.5 text-sm font-medium rounded-full transition-all whitespace-nowrap cursor-pointer bg-primary text-white":a.className="tag-pill px-4 py-1.5 text-sm font-medium rounded-full transition-all whitespace-nowrap cursor-pointer bg-transparent hover:bg-base-200 text-base-content"})}function m(){u()}function h(){document.querySelectorAll(".lang-filter-btn").forEach(e=>{e.getAttribute("data-lang")===t.lang?e.className="lang-filter-btn px-4 py-1.5 text-sm font-medium rounded-full transition-all whitespace-nowrap cursor-pointer bg-primary text-white":e.className="lang-filter-btn px-4 py-1.5 text-sm font-medium rounded-full transition-all whitespace-nowrap cursor-pointer bg-transparent hover:bg-base-100 text-base-content"})}function i(){const e=document.getElementById("active-filters-mobile"),a=document.getElementById("filter-chips"),n=document.getElementById("results-count");if(!e||!a)return;if(!(t.lang!=="all"||t.tag)){e.classList.add("hidden");return}e.classList.remove("hidden");let r=[];if(t.lang!=="all"){const f=t.lang==="pt"?"\u{1F1E7}\u{1F1F7} PT":"\u{1F1FA}\u{1F1F8} EN";r.push(`
        <button onclick="window.blogFilters.setLanguage('all')" class="inline-flex items-center gap-2 px-3 py-1.5 bg-primary/10 text-primary rounded-full text-sm font-medium hover:bg-primary/20 transition-colors">
          <span>${f}</span>
          <svg class="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
        </button>
      `)}if(t.tag){const f=t.tag.charAt(0).toUpperCase()+t.tag.slice(1);r.push(`
        <button onclick="window.blogFilters.clearTag()" class="inline-flex items-center gap-2 px-3 py-1.5 bg-primary/10 text-primary rounded-full text-sm font-medium hover:bg-primary/20 transition-colors">
          <span>${f}</span>
          <svg class="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
        </button>
      `)}a.innerHTML=r.join("");const g=document.querySelectorAll('.article-card:not([style*="display: none"])').length;n.innerHTML=`Showing ${g} article${g!==1?"s":""}`}function s(){return window.location.pathname.includes("/articles/")}window.blogFilters={setLanguage(e){if(localStorage.setItem("blog-filter-lang",e),s()){const a=new URLSearchParams;e!=="all"&&a.set("lang",e),window.location.href="/"+(a.toString()?"?"+a.toString():"");return}t.lang=e,c({lang:e,page:1}),h(),u(),o(),i()},setTag(e){if(e?localStorage.setItem("blog-filter-tag",e):localStorage.removeItem("blog-filter-tag"),s()){const a=new URLSearchParams;a.set("tag",e),window.location.href="/?"+a.toString();return}t.tag===e?(t.tag=null,localStorage.removeItem("blog-filter-tag")):t.tag=e,c({tag:t.tag,page:1}),u(),o(),i()},clearTag(){if(localStorage.removeItem("blog-filter-tag"),s()){window.location.href="/";return}t.tag=null,c({tag:null,page:1}),u(),o(),i()},remove(e){e==="lang"?this.setLanguage("all"):e==="tag"&&this.setTag(t.tag)},clearAll(){t.lang="all",t.tag=null,c({lang:null,tag:null,page:1}),h(),m(),o(),i()},getFilters(){return{...t}},init(){if(s()){let a=!1,n=!1;if(document.referrer)try{const l=new URL(document.referrer);if(l.origin===window.location.origin){const r=new URLSearchParams(l.search),d=r.get("lang"),g=r.get("tag");d&&(t.lang=d,a=!0),g&&(t.tag=g,n=!0)}}catch{}if(a||(t.lang=localStorage.getItem("blog-filter-lang")||"all"),!n){const l=localStorage.getItem("blog-filter-tag");t.tag=l||null}}else{const a=b();t.lang=a.lang,t.tag=a.tag,t.search=a.search,localStorage.setItem("blog-filter-lang",t.lang),t.tag?localStorage.setItem("blog-filter-tag",t.tag):localStorage.removeItem("blog-filter-tag")}const e=document.getElementById("search-input");e&&t.search&&!s()&&(e.value=t.search)}};async function w(){await y(),window.blogFilters.init(),m(),o(),i()}document.readyState==="loading"?document.addEventListener("DOMContentLoaded",w):w()})();
