(function(){let m=[],e={lang:"all",tag:null,search:""};function b(){const t=new URLSearchParams(window.location.search);return{lang:t.get("lang")||"all",tag:t.get("tag")||null,search:t.get("q")||"",page:parseInt(t.get("page"))||1}}function u(t){const a=new URLSearchParams(window.location.search);Object.entries(t).forEach(([l,n])=>{n===null||n===""||n==="all"||n===1?a.delete(l):a.set(l,n)});const r=a.toString()?`${window.location.pathname}?${a.toString()}`:window.location.pathname;window.history.pushState({},"",r)}async function S(){try{m=await(await fetch("/tags.json")).json()}catch(t){console.error("Failed to load tags:",t),m=[]}}function i(){requestAnimationFrame(()=>{const t=document.querySelectorAll(".article-card"),a=[],r=[];t.forEach(l=>{let n=!0;if(e.lang!=="all"){const o=l.getAttribute("data-language")||"en";e.lang==="pt"?n=n&&(o==="pt-BR"||o==="pt"):n=n&&o===e.lang}if(e.tag){const o=l.getAttribute("data-tags")||"";n=n&&o.includes(e.tag.toLowerCase())}n?a.push(l):r.push(l)}),a.forEach(l=>l.classList.remove("js-hidden")),r.forEach(l=>l.classList.add("js-hidden")),window.pagination&&window.pagination.handleSearch&&window.pagination.handleSearch()})}function d(){document.querySelectorAll(".tag-pill").forEach(a=>{const r=a.getAttribute("data-tag");r==="all"&&!e.tag||r===e.tag?a.className="tag-pill px-4 py-1.5 text-sm font-medium rounded-full whitespace-nowrap cursor-pointer bg-primary text-white":a.className="tag-pill px-4 py-1.5 text-sm font-medium rounded-full whitespace-nowrap cursor-pointer bg-transparent hover:bg-base-200 text-base-content"})}function p(){d()}function h(){document.querySelectorAll(".lang-filter-btn").forEach(t=>{t.getAttribute("data-lang")===e.lang?t.className="lang-filter-btn px-4 py-1.5 text-sm font-medium rounded-full whitespace-nowrap cursor-pointer bg-primary text-white":t.className="lang-filter-btn px-4 py-1.5 text-sm font-medium rounded-full whitespace-nowrap cursor-pointer bg-transparent hover:bg-base-100 text-base-content"})}function s(){const t=document.getElementById("active-filters-mobile"),a=document.getElementById("filter-chips"),r=document.getElementById("results-count");if(!t||!a)return;if(!(e.lang!=="all"||e.tag)){t.classList.add("hidden");return}t.classList.remove("hidden");let n=[];if(e.lang!=="all"){const f=e.lang==="pt"?"\u{1F1E7}\u{1F1F7} PT":"\u{1F1FA}\u{1F1F8} EN";n.push(`
        <button onclick="window.blogFilters.setLanguage('all')" class="inline-flex items-center gap-2 px-3 py-1.5 bg-primary/10 text-primary rounded-full text-sm font-medium hover:bg-primary/20 transition-colors">
          <span>${f}</span>
          <svg class="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
        </button>
      `)}if(e.tag){const f=e.tag.charAt(0).toUpperCase()+e.tag.slice(1);n.push(`
        <button onclick="window.blogFilters.clearTag()" class="inline-flex items-center gap-2 px-3 py-1.5 bg-primary/10 text-primary rounded-full text-sm font-medium hover:bg-primary/20 transition-colors">
          <span>${f}</span>
          <svg class="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
        </button>
      `)}a.innerHTML=n.join("");const c=document.querySelectorAll(".article-card:not(.js-hidden)").length;r.innerHTML=`Showing ${c} article${c!==1?"s":""}`}function g(){return window.location.pathname.includes("/articles/")}window.blogFilters={setLanguage(t){if(localStorage.setItem("blog-filter-lang",t),g()){const a=new URLSearchParams;t!=="all"&&a.set("lang",t),window.location.href="/"+(a.toString()?"?"+a.toString():"");return}e.lang=t,u({lang:t,page:1}),h(),d(),i(),s()},setTag(t){if(t?localStorage.setItem("blog-filter-tag",t):localStorage.removeItem("blog-filter-tag"),g()){const a=new URLSearchParams;a.set("tag",t),window.location.href="/?"+a.toString();return}e.tag===t?(e.tag=null,localStorage.removeItem("blog-filter-tag")):e.tag=t,u({tag:e.tag,page:1}),d(),i(),s()},clearTag(){if(localStorage.removeItem("blog-filter-tag"),g()){window.location.href="/";return}e.tag=null,u({tag:null,page:1}),d(),i(),s()},remove(t){t==="lang"?this.setLanguage("all"):t==="tag"&&this.setTag(e.tag)},clearAll(){e.lang="all",e.tag=null,u({lang:null,tag:null,page:1}),h(),p(),i(),s()},getFilters(){return{...e}},init(){if(g()){let a=!1,r=!1;if(document.referrer)try{const l=new URL(document.referrer);if(l.origin===window.location.origin){const n=new URLSearchParams(l.search),o=n.get("lang"),c=n.get("tag");o&&(e.lang=o,a=!0),c&&(e.tag=c,r=!0)}}catch{}if(a||(e.lang=localStorage.getItem("blog-filter-lang")||"all"),!r){const l=localStorage.getItem("blog-filter-tag");e.tag=l||null}}else{const a=b();e.lang=a.lang,e.tag=a.tag,e.search=a.search,localStorage.setItem("blog-filter-lang",e.lang),e.tag?localStorage.setItem("blog-filter-tag",e.tag):localStorage.removeItem("blog-filter-tag")}const t=document.getElementById("search-input");t&&e.search&&!g()&&(t.value=e.search)}};async function w(){await S(),window.blogFilters.init(),p(),i(),s()}document.readyState==="loading"?document.addEventListener("DOMContentLoaded",w):w()})();
